name: asp
channels:
  - potassco
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - notebook
  - ipykernel
  - clingo=5.4.0
  - asprin=3.1.1
  - jupyter_client=5.3.3
  - jupyter_core
  - ipython
  - pip
